import os

RPC_URL = os.getenv("RPC_URL")
CHAIN_ID = int(os.getenv("CHAIN_ID", "31337"))

BACKEND_PRIVATE_KEY = os.getenv("BACKEND_PRIVATE_KEY")

LOAN_ESCROW_ADDRESS = os.getenv("LOAN_ESCROW_ADDRESS")
REPUTATION_REGISTRY_ADDRESS = os.getenv("REPUTATION_REGISTRY_ADDRESS")
INSURANCE_POOL_ADDRESS = os.getenv("INSURANCE_POOL_ADDRESS")
LIQUIDITY_POOL_ADDRESS = os.getenv("LIQUIDITY_POOL_ADDRESS")

if not all([
    RPC_URL,
    BACKEND_PRIVATE_KEY,
    LOAN_ESCROW_ADDRESS,
    REPUTATION_REGISTRY_ADDRESS,
    INSURANCE_POOL_ADDRESS,
    LIQUIDITY_POOL_ADDRESS
]):
    raise RuntimeError("❌ Missing required environment variables")
